### ISSUE TITLE
Unsigned framework issue

### ISSUE THREAD

**Issue by demerzel3** [FlorianHubl/ElectrumKit#1]
Hey! Sorry this is probably a noob question I've started using Swift and XCode very recently. 

---

I'm trying to use `ElectrumKit` in my project, I've added it like this to my `Package`:
```
        .package(url: "https://github.com/FlorianHubl/ElectrumKit", branch: "main"),
```

After doing the above I'm getting a bunch of errors related to `LibWally` that all look like this:
```
.../SourcePackages/checkouts/LibWally/LibWally.xcframework:1:1 While building for macOS, no library for this platform was found in '.../SourcePackages/checkouts/LibWally/LibWally.xcframework'.
```

When I click on one of the errors I get this modal from XCode:
<img width="273" alt="Screenshot 2023-10-14 at 22 29 39" src="https://github.com/FlorianHubl/ElectrumKit/assets/442835/e07760cb-6740-4b5a-9589-6bc7a259ed2a">

Clicking "Accept Unsigned" makes the error go away, only to pop back up at the next build run. Do you know how I can escape this loop?

The [linked help article](https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks) in the modal isn't very helpful, it doesn't cover this specific case.

Thanks a lot!

**Comment by FlorianHubl** [comment]
I think I know what's going on here. The problem is that I have exported the LibWally.xcframework from the official GitHub Repository and not signed it. ElectrumKit is using LibWally to decode Bitcoin addresses in the correct format. I will try to solve this problem in a few days. Please keep in mind that ElectrumKit is still in a very early development stage and may therefore still maybe have bugs or be very slow in some cases.

**Comment by FlorianHubl** [comment]
The LibWally XCFramework only supports iOS and not macOS. What happens if you build it on iOS?

**Comment by demerzel3** [comment]
Not sure if you changed anything, but I retried this today and it worked flawlessly both on my mac and iPhone.

I'm going to close the issue, thanks a lot for looking into it 🙌
